### ISSUE TITLE
Update npm readme

### ISSUE THREAD

**Issue by jimbuck** [takempf/Igneous#9]
You just might want to update the npm readme to include your "This project is no longer being actively maintained" message. I just created a very small javascript library called [IgneousJS](https://github.com/JimmyBoh/IgneousJS), but first did a check for others that are similarly named.  I saw yours and just wanted to let you know.

**Comment by takempf** [comment]
I should probably just remove it from npm entirely, if that's possible.

**Comment by jimbuck** [comment]
I would leave it, who knows if anybody has any projects that depend on it? Or some might find it useful as reference code. Very nice logo, btw.

**Comment by jimbuck** [comment]
I've moved on to other projects, so feel free to ignore this if you'd like.
